### ISSUE TITLE
Error Friend Reguest in phpBB 3.2

### ISSUE THREAD

**Issue by fonziset** [florinp/phpbb-messenger#38]
Fatal error: Uncaught Error: Call to a member function load_user_by_username() on null in /nfsmnt/hosting2_2/1/f/1fe298cf-4d7c-421e-963f-d248105873d9/...../web/ext/florinp/messenger/notification/type/friend_request.php:76 Stack trace: #0 /nfsmnt/hosting2_2/1/f/1fe298cf-4d7c-421e-963f-d248105873d9/.../web/phpbb/notification/type/base.php(291): pokecaj\messenger\notification\type\friend_request->get_avatar() #1 /nfsmnt/hosting2_2/1/f/1fe298cf-4d7c-421e-963f-d248105873d9/florinp/web/includes/functions.php(4331): phpbb\notification\type\base->prepare_for_display() #2 /nfsmnt/hosting2_2/1/f/1fe298cf-4d7c-421e-963f-d248105873d9/pokecaj.sk/web/index.php(238): page_header('Hlavn\xC3\xA1 str\xC3\xA1nk...', true) #3 {main} thrown in /nfsmnt/hosting2_2/1/f/1fe298cf-4d7c-421e-963f-d248105873d9/.../web/ext/florinp/messenger/notification/type/friend_request.php on line 76

**Comment by Galixte** [comment]
Hi @florinp,

could you take a look, please ?
